import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

type Profile = "local" | "production-runtime" | "offline-content";

interface EnvLine {
  key?: string;
  value?: string;
  comment?: string;
  blank?: boolean;
}

interface Args {
  profile: Profile;
  envPath: string;
  print: boolean;
  force: boolean;
  help: boolean;
}

const profileValues = ["local", "production-runtime", "offline-content"] as const;
const secretCommand =
  "node -e \"console.log(require('node:crypto').randomBytes(48).toString('base64url'))\"";

function randomSecret() {
  return randomBytes(48).toString("base64url");
}

function parseProfile(value: string): Profile {
  if (profileValues.includes(value as Profile)) {
    return value as Profile;
  }

  throw new Error(`Unsupported profile: ${value}. Use ${profileValues.join(", ")}.`);
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    profile: "local",
    envPath: path.resolve(import.meta.dirname, "..", ".env"),
    print: false,
    force: false,
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg) {
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      args.help = true;
      continue;
    }

    if (arg === "--print") {
      args.print = true;
      continue;
    }

    if (arg === "--force") {
      args.force = true;
      continue;
    }

    if (arg === "--profile") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--profile requires a value.");
      }
      args.profile = parseProfile(value);
      index += 1;
      continue;
    }

    if (arg.startsWith("--profile=")) {
      args.profile = parseProfile(arg.slice("--profile=".length));
      continue;
    }

    if (arg === "--path") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--path requires a value.");
      }
      args.envPath = path.resolve(value);
      index += 1;
      continue;
    }

    if (arg.startsWith("--path=")) {
      args.envPath = path.resolve(arg.slice("--path=".length));
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return args;
}

function line(key: string, value: string): EnvLine {
  return { key, value };
}

function comment(value: string): EnvLine {
  return { comment: value };
}

function blank(): EnvLine {
  return { blank: true };
}

function buildCommonLines(profile: Profile): EnvLine[] {
  const production = profile !== "local";
  const appUrl = production ? "https://round1.example.com" : "https://round1.local";

  return [
    comment(`Generated by npm run env:init -- --profile ${profile}`),
    comment(
      "Code defaults live in config/env.ts. Keep .env for secrets, hostnames, and real service credentials.",
    ),
    comment(
      "Redis, worker, sandbox, pool, session, rate-limit, PM2, healthcheck, and trust-proxy defaults do not need local overrides.",
    ),
    blank(),
    comment("Core runtime"),
    line("NODE_ENV", production ? "production" : "development"),
    line(
      "DATABASE_URL",
      production
        ? "postgres://round1:REPLACE_WITH_DB_PASSWORD@127.0.0.1:4397/round1"
        : "postgres://round1:round1_dev@127.0.0.1:4397/round1",
    ),
    line("APP_PUBLIC_URL", appUrl),
    line("APP_API_ORIGIN", appUrl),
    blank(),
    comment(`Generate SESSION_SECRET with: ${secretCommand}`),
    line("SESSION_SECRET", randomSecret()),
    comment(`Generate TOTP_ENCRYPTION_KEK with: ${secretCommand}`),
    line("TOTP_ENCRYPTION_KEK", randomSecret()),
    comment(`Optional initial admin bootstrap password. Generate with: ${secretCommand}`),
    line("ROUND1_INITIAL_ADMIN_PASSWORD", ""),
    blank(),
    comment("Mail provider credentials"),
    line("MAIL_PROVIDER", "resend"),
    line("MAIL_FROM", production ? "Round1 <no-reply@round1.example.com>" : ""),
    line("RESEND_API_KEY", ""),
    comment("POSTMARK_SERVER_TOKEN="),
    comment("TENCENT_SES_SECRET_ID="),
    comment("TENCENT_SES_SECRET_KEY="),
    comment("TENCENT_SES_REGION=ap-hongkong"),
    blank(),
    comment("Bot protection"),
    line("AUTH_TURNSTILE_SITE_KEY", ""),
    line("AUTH_TURNSTILE_SECRET_KEY", ""),
    blank(),
    comment("Third-party identity"),
    line("CPPLEARN_OIDC_ISSUER", ""),
    line("CPPLEARN_OIDC_CLIENT_ID", ""),
    line("CPPLEARN_OIDC_CLIENT_SECRET", ""),
    line("CPPLEARN_OIDC_REDIRECT_URI", ""),
    comment("QQ_CONNECT_CLIENT_ID="),
    comment("QQ_CONNECT_CLIENT_SECRET="),
    comment("QQ_CONNECT_REDIRECT_URI="),
    blank(),
    comment("Public assets"),
    line("R2_PUBLIC_BASE_URL", ""),
  ];
}

function buildLlmLines(): EnvLine[] {
  return [
    blank(),
    comment("Offline content LLM lane"),
    line("LLM_PROVIDER_DEFAULT", "openrouter"),
    line("LLM_PROVIDER_BACKUP", ""),
    line("OPENROUTER_API_KEY", ""),
    line("OPENROUTER_MODEL", "openai/gpt-5.4"),
    line("DEEPSEEK_API_KEY", ""),
    line("DEEPSEEK_MODEL", "deepseek-v4-pro"),
    line("LLM_REASONING_DEFAULT", "max>xhigh>high>medium>default"),
    line("LLM_THINKING_TYPE_DEFAULT", "enabled"),
    line("LLM_THINKING_BUDGET_DEFAULT", "default"),
    line("LLM_REASONING_SUMMARY_DEFAULT", "auto"),
  ];
}

function buildProfileLines(profile: Profile): EnvLine[] {
  const lines = buildCommonLines(profile);

  if (profile === "offline-content") {
    lines.push(
      blank(),
      comment("Offline content environment"),
      line("ROUND1_PM2_ENABLE_CONTENT_WORKER", "1"),
      line("SANDBOX_RUNNER_URL", "http://127.0.0.1:4401"),
      ...buildLlmLines(),
    );
  }

  return lines;
}

function renderEnv(lines: EnvLine[]) {
  return `${lines
    .map((item) => {
      if (item.blank) return "";
      if (item.comment !== undefined) return `# ${item.comment}`;
      return `${item.key}=${item.value ?? ""}`;
    })
    .join("\n")}\n`;
}

function printHelp() {
  console.log(`Usage: npm run env:init -- [options]

Options:
  --profile <name>  local | production-runtime | offline-content (default: local)
  --path <file>     Output path (default: project .env)
  --print           Print the generated file instead of writing it
  --force           Overwrite an existing .env file
  --help            Show this help

Secret generation command:
  ${secretCommand}

Examples:
  npm run env:init -- --profile local --print
  npm run env:init -- --profile production-runtime --force
  npm run env:init -- --profile offline-content --path .env.offline --force`);
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    return;
  }

  const output = renderEnv(buildProfileLines(args.profile));

  if (args.print) {
    process.stdout.write(output);
    return;
  }

  if (fs.existsSync(args.envPath) && !args.force) {
    throw new Error(
      `${args.envPath} already exists. Use --print to review or --force to overwrite.`,
    );
  }

  fs.mkdirSync(path.dirname(args.envPath), { recursive: true });
  fs.writeFileSync(args.envPath, output, { encoding: "utf8", mode: 0o600 });

  try {
    fs.chmodSync(args.envPath, 0o600);
  } catch {
    // Windows may ignore POSIX permissions; the deploy checklist still covers file ACLs.
  }

  console.log(`Wrote ${args.envPath} for profile ${args.profile}.`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
